/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laboratorio2_oyecutey;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author yecut
 */

public class LoginFrameJava extends javax.swing.JFrame {
    
    private int intentos = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrameJava.class.getName());

    /**
     * Creates new form LoginFrameJava
     */
    public LoginFrameJava() {
    initComponents();
    this.setLocationRelativeTo(null);
    
    getRootPane().setDefaultButton(BTNINICIARSESION);
    
    TXTUSUARIO.addActionListener(e -> iniciarSesion());
    PASSWORD.addActionListener(e -> iniciarSesion());

    SetImageLabel(IMAGEN1, "/imagenes/552721.png");
    SetImageLabel(IMAGEN2, "/imagenes/password-76.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        LOGIN = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTUSUARIO = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        LBLUSUARIO = new javax.swing.JLabel();
        LBLCONTRASEÑA = new javax.swing.JLabel();
        BTNINICIARSESION = new javax.swing.JButton();
        IMAGEN2 = new javax.swing.JLabel();
        IMAGEN1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOGIN.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        TXTUSUARIO.addActionListener(this::TXTUSUARIOActionPerformed);

        PASSWORD.addActionListener(this::PASSWORDActionPerformed);

        LBLUSUARIO.setBackground(new java.awt.Color(255, 255, 255));
        LBLUSUARIO.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        LBLUSUARIO.setText("USUARIO");

        LBLCONTRASEÑA.setBackground(new java.awt.Color(255, 255, 255));
        LBLCONTRASEÑA.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        LBLCONTRASEÑA.setText("CONTRASEÑA");

        BTNINICIARSESION.setBackground(new java.awt.Color(0, 0, 204));
        BTNINICIARSESION.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BTNINICIARSESION.setForeground(new java.awt.Color(255, 255, 255));
        BTNINICIARSESION.setText("INICIAR SESIÓN");
        BTNINICIARSESION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNINICIARSESIONMouseClicked(evt);
            }
        });
        BTNINICIARSESION.addActionListener(this::BTNINICIARSESIONActionPerformed);

        IMAGEN2.setBackground(new java.awt.Color(255, 255, 255));
        IMAGEN2.setForeground(new java.awt.Color(255, 255, 255));

        IMAGEN1.setBackground(new java.awt.Color(255, 255, 255));
        IMAGEN1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN);
        LOGIN.setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLCONTRASEÑA)
                    .addComponent(LBLUSUARIO))
                .addGap(10, 10, 10)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BTNINICIARSESION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTUSUARIO, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IMAGEN2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IMAGEN1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLUSUARIO)
                    .addComponent(IMAGEN1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLCONTRASEÑA)
                    .addComponent(IMAGEN2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNINICIARSESION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void SetImageLabel(JLabel labelName, String resourcePath) {
    java.net.URL url = getClass().getResource(resourcePath);

    if (url != null) {
        ImageIcon image = new ImageIcon(url);

        int ancho = labelName.getWidth();
        int alto = labelName.getHeight();

        if (ancho > 0 && alto > 0) {
            Image scaledImage = image.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            labelName.setIcon(new ImageIcon(scaledImage));
            labelName.setText("");
        }
    } else {
        System.out.println("No se encontró la imagen: " + resourcePath);
    }
}
    private void TXTUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTUSUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTUSUARIOActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void BTNINICIARSESIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNINICIARSESIONMouseClicked
        iniciarSesion();
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNINICIARSESIONMouseClicked
    private void iniciarSesion() {
    String Usuario = "oyecutey";
    String Contraseña = "Umariano24";

    String Password = new String(PASSWORD.getPassword());

    if (TXTUSUARIO.getText().equals(Usuario) && Password.equals(Contraseña)) {
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        dispose();
    } else {
        intentos++;

        if (intentos >= 3) {
            JOptionPane.showMessageDialog(this, "Ha superado los 3 intentos permitidos.");
            BTNINICIARSESION.setEnabled(false);
            TXTUSUARIO.setEnabled(false);
            PASSWORD.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos. Intento " + intentos + " de 3.");
        }
    }
}
    private void BTNINICIARSESIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINICIARSESIONActionPerformed
        iniciarSesion();
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNINICIARSESIONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrameJava().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNINICIARSESION;
    private javax.swing.JLabel IMAGEN1;
    private javax.swing.JLabel IMAGEN2;
    private javax.swing.JLabel LBLCONTRASEÑA;
    private javax.swing.JLabel LBLUSUARIO;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JTextField TXTUSUARIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
