/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.laboratorio2_oyecutey;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author yecut
 */
public class MantenimientoUsuarios extends javax.swing.JDialog {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoUsuarios.class.getName());
    
    private java.util.Map<String, String> clavesNuevas = new java.util.HashMap<>();
    /**
     * Creates new form MantenimientoUsuarios
     */
    public MantenimientoUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarUsuariosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTNOMBRE = new javax.swing.JTextField();
        TXTUSUARIO = new javax.swing.JTextField();
        COMBOBOXROL = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        COMBOBOXESTADO = new javax.swing.JComboBox<>();
        BTNCERRAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLAUSUARIOS = new javax.swing.JTable();
        BTNAGREGAR = new javax.swing.JButton();
        BTNMODIFICAR = new javax.swing.JButton();
        BTNINACTIVAR = new javax.swing.JButton();
        BTNLIMPIAR = new javax.swing.JButton();
        BTNELIMINAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANTENIMIENTO DE USUARIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("USUARIO:");

        jLabel4.setText("ROL:");

        TXTNOMBRE.addActionListener(this::TXTNOMBREActionPerformed);

        TXTUSUARIO.addActionListener(this::TXTUSUARIOActionPerformed);

        COMBOBOXROL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Jefe", "Empleado" }));
        COMBOBOXROL.addActionListener(this::COMBOBOXROLActionPerformed);

        jLabel5.setText("ESTADO:");

        COMBOBOXESTADO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        COMBOBOXESTADO.addActionListener(this::COMBOBOXESTADOActionPerformed);

        BTNCERRAR.setBackground(new java.awt.Color(255, 51, 51));
        BTNCERRAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNCERRAR.setText("CERRAR");
        BTNCERRAR.addActionListener(this::BTNCERRARActionPerformed);

        TABLAUSUARIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Rol", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLAUSUARIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLAUSUARIOSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLAUSUARIOS);
        TABLAUSUARIOS.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        BTNAGREGAR.setText("Agregar");
        BTNAGREGAR.addActionListener(this::BTNAGREGARActionPerformed);

        BTNMODIFICAR.setText("Modificar");
        BTNMODIFICAR.addActionListener(this::BTNMODIFICARActionPerformed);

        BTNINACTIVAR.setText("Inactivar");
        BTNINACTIVAR.addActionListener(this::BTNINACTIVARActionPerformed);

        BTNLIMPIAR.setText("Limpiar");
        BTNLIMPIAR.addActionListener(this::BTNLIMPIARActionPerformed);

        BTNELIMINAR.setText("Eliminar");
        BTNELIMINAR.addActionListener(this::BTNELIMINARActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNCERRAR)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TXTNOMBRE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TXTUSUARIO)
                                                .addComponent(COMBOBOXROL, 0, 223, Short.MAX_VALUE))))
                                    .addGap(48, 48, 48)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(COMBOBOXESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BTNAGREGAR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(BTNMODIFICAR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BTNINACTIVAR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BTNLIMPIAR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BTNELIMINAR))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(COMBOBOXESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COMBOBOXROL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNAGREGAR)
                    .addComponent(BTNMODIFICAR)
                    .addComponent(BTNINACTIVAR)
                    .addComponent(BTNLIMPIAR)
                    .addComponent(BTNELIMINAR))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNCERRAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBREActionPerformed

    private void TXTUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTUSUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTUSUARIOActionPerformed

    private void BTNCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARActionPerformed
                                        
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCERRARActionPerformed

    private void TABLAUSUARIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLAUSUARIOSMouseClicked
        int fila = TABLAUSUARIOS.getSelectedRow();

    if (fila == -1) {
        return;
    }

    TXTNOMBRE.setText(TABLAUSUARIOS.getValueAt(fila, 0).toString());
    TXTUSUARIO.setText(TABLAUSUARIOS.getValueAt(fila, 1).toString());
    COMBOBOXROL.setSelectedItem(TABLAUSUARIOS.getValueAt(fila, 2).toString());
    COMBOBOXESTADO.setSelectedItem(TABLAUSUARIOS.getValueAt(fila, 3).toString());

    String estado = TABLAUSUARIOS.getValueAt(fila, 3).toString();

    if (estado.equals("Inactivo")) {
        BTNINACTIVAR.setText("Activar");
    } else {
        BTNINACTIVAR.setText("Inactivar");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_TABLAUSUARIOSMouseClicked

    private void BTNAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAGREGARActionPerformed
        AsignarClaveUsuario ventanaClave = new AsignarClaveUsuario(null, true, TXTUSUARIO.getText().trim());
ventanaClave.setVisible(true);

String claveNueva = ventanaClave.getClaveAsignada();

if (claveNueva == null) {
    JOptionPane.showMessageDialog(this, "Debe asignar una contraseña para crear el usuario.");
    return;
}

clavesNuevas.put(TXTUSUARIO.getText().trim(), claveNueva);
        if (camposVacios()) return;
        if (usuarioDuplicado(TXTUSUARIO.getText().trim())) return;

    DefaultTableModel modelo = (DefaultTableModel) TABLAUSUARIOS.getModel();

    modelo.addRow(new Object[]{
        TXTNOMBRE.getText(),
        TXTUSUARIO.getText(),
        COMBOBOXROL.getSelectedItem().toString(),
        COMBOBOXESTADO.getSelectedItem().toString()
            
            
    });
    
    guardarTablaEnArchivo();
    limpiarCampos();// TODO add your handling code here:
    }//GEN-LAST:event_BTNAGREGARActionPerformed

    private void BTNMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMODIFICARActionPerformed

        int fila = TABLAUSUARIOS.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un usuario para modificar");
        return;
    }

    if (camposVacios()) return;
    if (usuarioDuplicadoAlModificar(TXTUSUARIO.getText().trim(), fila)) return;

    TABLAUSUARIOS.setValueAt(TXTNOMBRE.getText(), fila, 0);
    TABLAUSUARIOS.setValueAt(TXTUSUARIO.getText(), fila, 1);
    TABLAUSUARIOS.setValueAt(COMBOBOXROL.getSelectedItem().toString(), fila, 2);
    TABLAUSUARIOS.setValueAt(COMBOBOXESTADO.getSelectedItem().toString(), fila, 3);

    guardarTablaEnArchivo();
    limpiarCampos();
    // TODO add your handling code here:
    }//GEN-LAST:event_BTNMODIFICARActionPerformed

    private void BTNINACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINACTIVARActionPerformed
        
        int fila = TABLAUSUARIOS.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un usuario");
        return;
    }

    String estado = TABLAUSUARIOS.getValueAt(fila, 3).toString();

    if (estado.equals("Activo")) {
        TABLAUSUARIOS.setValueAt("Inactivo", fila, 3);
        COMBOBOXESTADO.setSelectedItem("Inactivo");
        BTNINACTIVAR.setText("Activar");
    } else {
        TABLAUSUARIOS.setValueAt("Activo", fila, 3);
        COMBOBOXESTADO.setSelectedItem("Activo");
        BTNINACTIVAR.setText("Inactivar");
    }  
        guardarTablaEnArchivo();// TODO add your handling code here:
    }//GEN-LAST:event_BTNINACTIVARActionPerformed

    private void BTNLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLIMPIARActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BTNLIMPIARActionPerformed

    private void BTNELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNELIMINARActionPerformed
           int fila = TABLAUSUARIOS.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un usuario para eliminar");
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro que desea eliminar este usuario?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        DefaultTableModel modelo = (DefaultTableModel) TABLAUSUARIOS.getModel();
        modelo.removeRow(fila);
        guardarTablaEnArchivo();
        limpiarCampos();
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_BTNELIMINARActionPerformed

    private void COMBOBOXROLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOBOXROLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOBOXROLActionPerformed

    private void COMBOBOXESTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOBOXESTADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOBOXESTADOActionPerformed

    private void limpiarCampos() {
    TXTNOMBRE.setText("");
    TXTUSUARIO.setText("");
    COMBOBOXROL.setSelectedIndex(0);
    COMBOBOXESTADO.setSelectedIndex(0);
    TABLAUSUARIOS.clearSelection();
    BTNINACTIVAR.setText("Inactivar");
    }
    
    private boolean camposVacios() {
        if (TXTNOMBRE.getText().trim().isEmpty() ||
            TXTUSUARIO.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor, ingrese los datos solicitados");
            return true;
        }

        return false;
    }
    private void guardarTablaEnArchivo() {
    DefaultTableModel modelo = (DefaultTableModel) TABLAUSUARIOS.getModel();
    java.util.List<String[]> usuarios = new java.util.ArrayList<>();

    for (int i = 0; i < modelo.getRowCount(); i++) {
        String nombre = modelo.getValueAt(i, 0).toString();
        String usuario = modelo.getValueAt(i, 1).toString();
        String rol = modelo.getValueAt(i, 2).toString();
        String estado = modelo.getValueAt(i, 3).toString();

        String clave = clavesNuevas.getOrDefault(usuario, "Temporal123!");

for (String[] u : ArchivoUsuarios.cargarUsuarios()) {
    if (u[1].equals(usuario) && !clavesNuevas.containsKey(usuario)) {
        clave = u[4];
        break;
    }
}

        usuarios.add(new String[]{
            nombre,
            usuario,
            rol,
            estado,
            clave
        });
    }
    
    

    ArchivoUsuarios.guardarUsuarios(usuarios);
}
    private void cargarUsuariosEnTabla() {
    DefaultTableModel modelo = (DefaultTableModel) TABLAUSUARIOS.getModel();
    modelo.setRowCount(0);

    for (String[] u : ArchivoUsuarios.cargarUsuarios()) {
        modelo.addRow(new Object[]{
            u[0],
            u[1],
            u[2],
            u[3]
        });
    }
}
    private boolean usuarioDuplicado(String usuario) {
    DefaultTableModel modelo = (DefaultTableModel) TABLAUSUARIOS.getModel();

    for (int i = 0; i < modelo.getRowCount(); i++) {
        String usuarioTabla = modelo.getValueAt(i, 1).toString();

        if (usuarioTabla.equalsIgnoreCase(usuario)) {
            JOptionPane.showMessageDialog(this, "El usuario ya existe. Ingrese otro nombre de usuario.");
            return true;
        }
    }

    return false;
}
    private boolean usuarioDuplicadoAlModificar(String usuario, int filaActual) {
    DefaultTableModel modelo = (DefaultTableModel) TABLAUSUARIOS.getModel();

    for (int i = 0; i < modelo.getRowCount(); i++) {
        if (i == filaActual) {
            continue;
        }

        String usuarioTabla = modelo.getValueAt(i, 1).toString();

        if (usuarioTabla.equalsIgnoreCase(usuario)) {
            JOptionPane.showMessageDialog(this, "El usuario ya existe. Ingrese otro nombre de usuario.");
            return true;
        }
    }

    return false;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MantenimientoUsuarios dialog = new MantenimientoUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAGREGAR;
    private javax.swing.JButton BTNCERRAR;
    private javax.swing.JButton BTNELIMINAR;
    private javax.swing.JButton BTNINACTIVAR;
    private javax.swing.JButton BTNLIMPIAR;
    private javax.swing.JButton BTNMODIFICAR;
    private javax.swing.JComboBox<String> COMBOBOXESTADO;
    private javax.swing.JComboBox<String> COMBOBOXROL;
    private javax.swing.JTable TABLAUSUARIOS;
    private javax.swing.JTextField TXTNOMBRE;
    private javax.swing.JTextField TXTUSUARIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
