/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laboratorio2_oyecutey;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Collections;
import javax.swing.JOptionPane;
/**
 *
 * @author yecut
 */
public class MenuUsuario extends javax.swing.JFrame {
    
    private java.util.List<String[]> listaActual = new java.util.ArrayList<>();
    
    private void cargarRegistros() {
    DefaultTableModel modelo = (DefaultTableModel) TABLAREGISTROS.getModel();
    modelo.setRowCount(0);

    listaActual.clear();

    List<String[]> registros = ArchivoActividades.cargarActividades();
    Collections.reverse(registros);

    for (String[] r : registros) {
        if (r.length == 5 && r[1].equals(usuarioActual)) {
            modelo.addRow(r);
            listaActual.add(r);
        }
    }
}

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName());

    private String usuarioActual;

    public MenuUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MenuUsuario(String usuario) {
    initComponents();
    this.usuarioActual = usuario;
    LBLBIENVENIDO.setText("Bienvenido: " + usuario);
    setLocationRelativeTo(null);
    cargarRegistros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTNREGISTRAR = new javax.swing.JButton();
        BTNCERRARSESION = new javax.swing.JButton();
        LBLBIENVENIDO = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLAREGISTROS = new javax.swing.JTable();
        BTNELIMINAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PANEL DE USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BTNREGISTRAR.setText("REGISTRAR ACTIVIDAD");
        BTNREGISTRAR.addActionListener(this::BTNREGISTRARActionPerformed);

        BTNCERRARSESION.setBackground(new java.awt.Color(255, 0, 0));
        BTNCERRARSESION.setText("CERRAR SESIÓN");
        BTNCERRARSESION.addActionListener(this::BTNCERRARSESIONActionPerformed);

        LBLBIENVENIDO.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        LBLBIENVENIDO.setText("Bienvenido");

        TABLAREGISTROS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Usuario", "Actividad", "Horas", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLAREGISTROS.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(TABLAREGISTROS);
        TABLAREGISTROS.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        BTNELIMINAR.setText("ELIMINAR ACTIVIDAD");
        BTNELIMINAR.addActionListener(this::BTNELIMINARActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBLBIENVENIDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNREGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNCERRARSESION, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNELIMINAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(249, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(LBLBIENVENIDO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNREGISTRAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(BTNELIMINAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNCERRARSESION)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed

    RegistrarActividad ventana = new RegistrarActividad(this, true, usuarioActual);
    ventana.setVisible(true);

    cargarRegistros();       // TODO add your handling code here:
    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    private void BTNCERRARSESIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARSESIONActionPerformed

    LoginFrameJava login = new LoginFrameJava();
    login.setVisible(true);
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCERRARSESIONActionPerformed

    private void BTNELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNELIMINARActionPerformed
    int fila = TABLAREGISTROS.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una actividad");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "¿Eliminar actividad?",
        "Confirmar",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    String[] seleccionada = listaActual.get(fila);

    List<String[]> todas = ArchivoActividades.cargarActividades();

    for (int i = 0; i < todas.size(); i++) {
        if (java.util.Arrays.equals(todas.get(i), seleccionada)) {
            todas.remove(i);
            break;
        }
    }

    ArchivoActividades.guardarLista(todas);
    cargarRegistros(); // TODO add your handling code here:
    }//GEN-LAST:event_BTNELIMINARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRARSESION;
    private javax.swing.JButton BTNELIMINAR;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JLabel LBLBIENVENIDO;
    private javax.swing.JTable TABLAREGISTROS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
