/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laboratorio2_oyecutey;

/**
 *
 * @author yecut
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTNINICIARSESION = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LBLMENU = new javax.swing.JLabel();
        LBLGESTION = new javax.swing.JLabel();
        BTNMANTENIMIENTO = new javax.swing.JButton();
        BTNREINICIO = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        BTNINICIARSESION.setBackground(new java.awt.Color(0, 0, 204));
        BTNINICIARSESION.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BTNINICIARSESION.setForeground(new java.awt.Color(255, 255, 255));
        BTNINICIARSESION.setText("INICIAR SESIÓN");
        BTNINICIARSESION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNINICIARSESIONMouseClicked(evt);
            }
        });
        BTNINICIARSESION.addActionListener(this::BTNINICIARSESIONActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        LBLMENU.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        LBLMENU.setForeground(new java.awt.Color(255, 255, 255));
        LBLMENU.setText("menu principal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(LBLMENU)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LBLMENU)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        LBLGESTION.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        LBLGESTION.setText("GESTIÓN");

        BTNMANTENIMIENTO.setText("Mantenimiento de Usuarios");
        BTNMANTENIMIENTO.addActionListener(this::BTNMANTENIMIENTOActionPerformed);

        BTNREINICIO.setText("Reinicio de clave");
        BTNREINICIO.addActionListener(this::BTNREINICIOActionPerformed);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CERRAR SESIÓN");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(LBLGESTION))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNMANTENIMIENTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNREINICIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LBLGESTION)
                .addGap(25, 25, 25)
                .addComponent(BTNMANTENIMIENTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNREINICIO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNINICIARSESIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNINICIARSESIONMouseClicked
    
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNINICIARSESIONMouseClicked

    private void BTNINICIARSESIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINICIARSESIONActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNINICIARSESIONActionPerformed

    private void BTNMANTENIMIENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMANTENIMIENTOActionPerformed
         this.setVisible(false);

        MantenimientoUsuarios ventana = new MantenimientoUsuarios(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

        this.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BTNMANTENIMIENTOActionPerformed

    private void BTNREINICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREINICIOActionPerformed
        this.setVisible(false);

        ReinicioClave ventana = new ReinicioClave(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

        this.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNREINICIOActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginFrameJava login = new LoginFrameJava();
        login.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNINICIARSESION;
    private javax.swing.JButton BTNMANTENIMIENTO;
    private javax.swing.JButton BTNREINICIO;
    private javax.swing.JLabel LBLGESTION;
    private javax.swing.JLabel LBLMENU;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
